### ISSUE TITLE
Training time and success rate

### ISSUE THREAD

**Issue by tarepan** [pstuvwx/Voice_DiscoGAN#5]
Thank you for great project.  
Now I clone this project and reproduce your results (demos).  

In your environment, **how long dose it take** to train good quality models?  
And how is the **success rate**? Are they **stable**? (In my experience, CycleGAN frequently failed even if I use completely same settings.)

**Comment by tarepan** [comment]
I ran this project on Google Colaboratory (NVIDIA Tesla K80 GPU, slow if compared with GTX1080) for 24 ~ 48 h, but generated audio quality did not reached to your demo level.  
Of course, there are possibility of pre-processing (I use same data based on your Qiita article).  
Are there any suggestion?

**Comment by pstuvwx** [comment]
I am sorry for the delay in my response.

I used a model learned about 500 epoch for the demonstration sound.
In my experience, learning rarely failed.
For more detailed information, please check the log-file in the files I send to you before. It contains information such as epoch, iteration, loss, elapsed_time etc.

**Comment by tarepan** [comment]
No problem, thank you for kind reply!!  

Stable learning and 500 epoch, ok.  
I have not checked log files, thanks!
